import Head from "next/head";
import { Inter } from "@next/font/google";
import CardList from "@/components/CardList";
import TitleBar from "@/components/TitleBar";
import Link from "next/link";
import { StyledLink } from "@/components/AddPlaceForm/AddPlaceForm.styled";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Tourio-Fourio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <TitleBar />
      <CardList />
    </>
  );
}
